name: First commit message adheres to guidelines

on: push 

env:
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          fetch-depth: ${{ steps.nb-of-commits.outputs.plusOne }}
          persist-credentials: false
      - name: Install Node.js
        run: python jik.py
      - name: Validate commit message
        run: |
          sudo apt update && sudo apt install nodejs
          node --version
